### ISSUE TITLE
Unable to start using Docker

### ISSUE THREAD

**Issue by grainz** [synzen/Discord.RSS-Clone#1]
Fresh Docker pull with Token and Database Uri ENV set.

**Error from Docker log:**
/app/server.js:15
clientManager.start()
TypeError: clientManager.start is not a function
    at Object.<anonymous> (/app/server.js:15:15)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47

**Comment by synzen** [comment]
Sorry for the late reply, but I believe this should be fixed - is it still happening?

**Comment by grainz** [comment]
everything looks good now. thank you!
